@startuml
title Arquitectura RTL del controlador LoRa
skinparam componentStyle rectangle

actor Host
component lora_command_fpga_manager as TOP
component myUart as UART
component command_decoder as DEC
component uart_response_serializer as RESP
component uart_rx_serializer as RXSER
component uart_tx_master as MASTER
component led_status_controller as LED
component sx1278_controller as CTRL
component sx1278_config_registers as REGS
component sx1278_frame_builder as BUILD
component spi_sequence_controller as SEQ
component spi_register_access as ACCESS
component spi_frame_controller as FRAME
component spi_pin_driver as PINS
component SX1278 as RADIO

Host <--> UART : UART 115200 8N1
UART --> DEC : byte + dataRd
DEC --> CTRL : CONFIG / RESET / TX / RX
CTRL --> DEC : busy
DEC --> RESP : ACK/NACK
CTRL --> RXSER : paquete RX
RESP --> MASTER : request / trama
RXSER --> MASTER : request / trama
MASTER --> UART : byte + dataWr
TOP --> LED : estados

CTRL --> REGS : escritura de configuración
REGS --> BUILD : parámetros
CTRL --> BUILD : operación + paso
BUILD --> SEQ : frame + último paso + read
SEQ --> ACCESS : acceso de 2 bytes
ACCESS --> FRAME : carga + start
FRAME --> PINS : transferencia de byte
PINS <--> RADIO : NSS/SCLK/MOSI/MISO
RADIO --> CTRL : DIO0
CTRL --> RADIO : RESET
@enduml
