@startuml
title MEF command_decoder

[*] --> WAIT_START
WAIT_START --> WAIT_COMMAND : dataRd && byte == '#'
WAIT_START --> WAIT_START : otros bytes
WAIT_COMMAND --> WAIT_PARAMETER : dataRd
WAIT_PARAMETER --> WAIT_VALUE : dataRd
WAIT_VALUE --> WAIT_CHECKSUM : dataRd
WAIT_CHECKSUM --> WAIT_END : dataRd
WAIT_END --> DECODE : dataRd && byte == '$'
WAIT_END --> RESPONSE : dataRd && byte != '$'\nNACK
DECODE --> RESPONSE : ACK si se acepta y lanza\nNACK si es inválido o busy
RESPONSE --> WAIT_START : response_start
@enduml
