@startuml
title MEF spi_register_access

[*] --> IDLE
IDLE --> LOAD_FIRST : start_i
LOAD_FIRST --> LOAD_SECOND : charge first byte
LOAD_SECOND --> START_FRAME : charge second byte
START_FRAME --> WAIT_FRAME : start transfer
WAIT_FRAME --> DONE : frame_done && !read
WAIT_FRAME --> SKIP_FIRST_RX : frame_done && read
SKIP_FIRST_RX --> WAIT_SECOND_RX : descartar RX de dirección
WAIT_SECOND_RX --> CAPTURE_RX
CAPTURE_RX --> DONE : registrar dato RX
DONE --> IDLE : done_o = 1
@enduml
