@startuml
title MEF sx1278_controller

[*] --> IDLE
IDLE --> SEQUENCE_START : CONFIG / TX / RX
SEQUENCE_START --> SEQUENCE_WAIT
SEQUENCE_WAIT --> SEQUENCE_DONE : sequence_done

SEQUENCE_DONE --> IDLE : CONFIG / TX_WRITE
SEQUENCE_DONE --> TX_WAIT_DIO0 : TX_START
TX_WAIT_DIO0 --> SEQUENCE_START : DIO0 rising\nOP_TX_CLEAR

SEQUENCE_DONE --> RX_WAIT_DIO0 : RX_SETUP
RX_WAIT_DIO0 --> SEQUENCE_START : DIO0 rising\nOP_RX_IRQ
SEQUENCE_DONE --> RX_IRQ_CHECK : OP_RX_IRQ
RX_IRQ_CHECK --> RX_ERROR : CRC error
RX_IRQ_CHECK --> SEQUENCE_START : OP_RX_LENGTH
SEQUENCE_DONE --> RX_LENGTH_CHECK : OP_RX_LENGTH
RX_LENGTH_CHECK --> SEQUENCE_START : OP_RX_ADDRESS o OP_RX_CLEAR
SEQUENCE_DONE --> SEQUENCE_START : OP_RX_ADDRESS\nOP_RX_POINTER
SEQUENCE_DONE --> SEQUENCE_START : OP_RX_POINTER\nOP_RX_FIFO
SEQUENCE_DONE --> RX_FIFO_CAPTURE : OP_RX_FIFO
RX_FIFO_CAPTURE --> SEQUENCE_START : otro byte o limpiar IRQ
RX_ERROR --> SEQUENCE_START : OP_RX_CLEAR
SEQUENCE_DONE --> RX_PACKET_DONE : OP_RX_CLEAR
RX_PACKET_DONE --> RX_WAIT_DIO0 : paquete disponible
@enduml
